--<ScriptOptions statementTerminator="GO"/>

ALTER TABLE "dbo"."Animal" DROP CONSTRAINT "PK__Animal__D4D8D0C62A4B4B5E"
GO

DROP TABLE "dbo"."Animal"
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE "dbo"."Animal" (
	"idVatNuoi" null NOT NULL,
	"Vatnuoi_name" null,
	CONSTRAINT "PK__Animal__D4D8D0C62A4B4B5E" PRIMARY KEY ("idVatNuoi") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

SET ANSI_PADDING OFF
GO

