--<ScriptOptions statementTerminator="GO"/>

ALTER TABLE "dbo"."News" DROP CONSTRAINT "PK__News__62FD89E931EC6D26"
GO

DROP TABLE "dbo"."News"
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE "dbo"."News" (
	"idNews" INT NOT NULL,
	"Title" null,
	"LinktoWeb" null,
	CONSTRAINT "PK__News__62FD89E931EC6D26" PRIMARY KEY ("idNews") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

SET ANSI_PADDING OFF
GO

